In [1]:
import pandas as pd

### Juntando os dois datasets.

In [3]:
# dataframe 1
df1 = pd.read_csv("gasolina_2000.csv", index_col=0)

df1

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52802,2010-12-26,2011-01-01,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL,574,R$/l,1.983,0.086,1.779,2.280,0.255,0.043,1.728,0.04,1.609,1.8536,0.023
52803,2010-12-26,2011-01-01,SUDESTE,SAO PAULO,ÓLEO DIESEL,1871,R$/l,1.966,0.070,1.699,2.399,0.261,0.036,1.705,0.045,1.5764,1.969,0.026
52804,2010-12-26,2011-01-01,SUL,PARANA,ÓLEO DIESEL,469,R$/l,1.946,0.058,1.799,2.109,0.19,0.030,1.756,0.038,1.659,1.9268,0.022
52805,2010-12-26,2011-01-01,SUL,RIO GRANDE DO SUL,ÓLEO DIESEL,419,R$/l,2.052,0.059,1.890,2.310,0.267,0.029,1.785,0.039,1.677,1.9172,0.022
52806,2010-12-26,2011-01-01,SUL,SANTA CATARINA,ÓLEO DIESEL,328,R$/l,2.018,0.066,1.849,2.210,0.225,0.033,1.793,0.042,1.7,1.8854,0.023

In [4]:
# dataframe 2
df2 = pd.read_csv("gasolina_2010.csv", index_col=0)

df2

C:\Users\Matheus\AppData\Local\Temp\ipykernel_31632\470409714.py:2: DtypeWarning: Columns (12,14,15,16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv("gasolina_2010.csv", index_col=0)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
9256,2011-01-02,2011-01-08,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,80,R$/l,2.030,0.003,2.020,2.050,0.411,0.001,1.619,0.013,1.6111,1.6411,0.008
9257,2011-01-02,2011-01-08,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,255,R$/l,1.717,0.102,1.490,1.990,0.225,0.059,1.492,0.069,1.3221,1.6201,0.046
9258,2011-01-02,2011-01-08,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,141,R$/l,1.848,0.148,1.590,2.490,0.326,0.080,1.522,0.105,1.2833,1.7486,0.069
9259,2011-01-02,2011-01-08,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,132,R$/l,1.893,0.108,1.699,2.199,0.191,0.057,1.702,0.04,1.5915,1.79,0.024
9260,2011-01-02,2011-01-08,NORDESTE,ALAGOAS,ETANOL HIDRATADO,97,R$/l,2.026,0.084,1.749,2.100,0.268,0.041,1.758,0.042,1.63,1.848,0.024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,4.690,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,-99999.0,0.046,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,4.699,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

In [5]:
# juntando ambos

df = pd.concat([df1, df2])

df

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,4.690,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,-99999.0,0.046,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,4.699,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

### Investigue as colunas e entenda o conjunto de dados usando head() e info()

In [6]:
df.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 120823 entries, 0 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   120823 non-null  object
 1   DATA FINAL                     120823 non-null  object
 2   REGIÃO                         120823 non-null  object
 3   ESTADO                         120823 non-null  object
 4   PRODUTO                        120823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 6   UNIDADE DE MEDIDA              120823 non-null  object
 7   PREÇO MÉDIO REVENDA            120823 non-null  float64
 8   DESVIO PADRÃO REVENDA          120823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           120823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 11  MARGEM MÉDIA REVENDA           120823 non-null  object
 12  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       120823 non-null  object
 14  DESVIO PADRÃO DISTRIBUIÇÃO     120823 non-null  object
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      120823 non-null  object
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      120823 non-null  object
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  object
dtypes: float64(5), int64(1), object(12)
memory usage: 17.5+ MB

### Selecione a terceira entrada da coluna DATA INICIAL e verifique seu tipo.

In [10]:
type(df["DATA INICIAL"][2])

str

### Converta o DATA INICIAL e DATA FINAL para datetime.

In [11]:
df["DATA INICIAL"] = pd.to_datetime(df["DATA INICIAL"])
df["DATA FINAL"] = pd.to_datetime(df["DATA FINAL"])

In [12]:
type(df["DATA INICIAL"].iloc[2])

pandas._libs.tslibs.timestamps.Timestamp

In [13]:
df["DATA INICIAL"][2]

Timestamp('2004-05-09 00:00:00')

### Crie uma nova coluna para apresentar o ano e o mês (aaaa-mm) utilizando a coluna DATA FINAL como referência.

In [14]:
df["ANO-MES"] = df["DATA FINAL"].apply(lambda x: '{}'.format(x.year)) + df["DATA FINAL"].apply(lambda x: '--{:02d}'.format(x.month))

In [17]:
df["ANO-MES"]

0         2004--05
1         2004--05
2         2004--05
3         2004--05
4         2004--05
            ...
120818    2021--05
120819    2021--05
120820    2021--05
120821    2021--05
120822    2021--05
Name: ANO-MES, Length: 120823, dtype: object

### Liste todos os tipos de produtos na base de dados.

In [19]:
df["PRODUTO"].value_counts()

PRODUTO
GASOLINA COMUM        23570
GLP                   23561
ETANOL HIDRATADO      23440
ÓLEO DIESEL           21194
GNV                   14469
ÓLEO DIESEL S10        9113
OLEO DIESEL S10        2376
OLEO DIESEL            2351
GASOLINA ADITIVADA      749
Name: count, dtype: int64

### Filtre o DataFrame para obter apenas dados da 'GASOLINA COMUM'. Grave em uma nova variável.

In [20]:
df_filtro = df["PRODUTO"] == "GASOLINA COMUM"

In [21]:
df2 = df[df_filtro]

In [23]:
df2.shape

(23570, 19)

In [24]:
df2

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,ANO-MES
12064,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,GASOLINA COMUM,128,R$/l,2.029,0.007,1.990,2.070,0.318,0.003,1.711,0.02,1.651,1.7427,0.012,2004--05
12065,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,GASOLINA COMUM,395,R$/l,2.025,0.062,1.850,2.220,0.296,0.031,1.729,0.036,1.6643,1.915,0.021,2004--05
12066,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,GASOLINA COMUM,194,R$/l,2.358,0.066,2.000,2.540,0.472,0.028,1.886,0.068,1.75,2.0713,0.036,2004--05
12067,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,GASOLINA COMUM,166,R$/l,2.120,0.075,1.970,2.440,0.325,0.035,1.795,0.033,1.70701,1.9703,0.018,2004--05
12068,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,GASOLINA COMUM,106,R$/l,2.090,0.034,2.000,2.159,0.35,0.016,1.74,0.042,1.6789,1.918,0.024,2004--05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120721,2021-04-25,2021-05-01,NORTE,RORAIMA,GASOLINA COMUM,12,R$/l,5.364,0.065,5.310,5.530,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021--05
120722,2021-04-25,2021-05-01,SUL,SANTA CATARINA,GASOLINA COMUM,119,R$/l,5.051,0.251,4.640,5.599,-99999.0,0.050,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021--05
120723,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GASOLINA COMUM,1187,R$/l,5.265,0.218,4.279,6.099,-99999.0,0.041,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021--05
120724,2021-04-25,2021-05-01,NORDESTE,SERGIPE,GASOLINA COMUM,34,R$/l,5.586,0.088,5.410,5.699,-99999.0,0.016,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021--05
120725,2021-04-25,2021-05-01,NORTE,TOCANTINS,GASOLINA COMUM,20,R$/l,5.751,0.160,5.578,6.119,-99999.0,0.028,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021--05

### Qual o preço médio da revenda da gasolina em agosto de 2008?

In [34]:
df2[df2['ANO-MES'] == '2008--08']["PREÇO MÉDIO REVENDA"].mean()

2.6012444444444442

### Qual o preço médio de revenda da gasolina em maio de 2014 em São Paulo?

In [35]:
df2[(df2["ANO-MES"] == '2014--05') & (df2['ESTADO'] == 'SAO PAULO')]["PREÇO MÉDIO REVENDA"].mean()

2.8822

### Você conseguiria descobrir em qual(quais) estado(s) a gasolina ultrapassou a barreira dos R$ 5,00? E quando isso ocorreu?

In [36]:
df2[df2["PREÇO MÉDIO REVENDA"] > 5][["ESTADO", "ANO-MES", "PREÇO MÉDIO REVENDA"]]

                ESTADO   ANO-MES  PREÇO MÉDIO REVENDA
98201             ACRE  2018--05                5.053
98347             ACRE  2018--06                5.035
98493             ACRE  2018--06                5.038
98511   RIO DE JANEIRO  2018--06                5.016
98646             ACRE  2018--06                5.031
...                ...       ...                  ...
120721         RORAIMA  2021--05                5.364
120722  SANTA CATARINA  2021--05                5.051
120723       SAO PAULO  2021--05                5.265
120724         SERGIPE  2021--05                5.586
120725       TOCANTINS  2021--05                5.751

[353 rows x 3 columns]

### Qual a média de preço dos estados da região sul em 2012?

In [42]:
df_aux = df2[df2["DATA FINAL"].apply(lambda x: x.year) == 2012]

df_aux[df_aux["REGIÃO"] == "SUL"]["PREÇO MÉDIO REVENDA"].mean()

2.7214423076923073

### Você conseguiria obter uma tabela contendo a variação percentual ano a ano para o estado do Rio de Janeiro?

In [43]:
df2["MES"] = df2["DATA FINAL"].apply(lambda x: x.month)
df_rio = df2[df2["ESTADO"] == "RIO DE JANEIRO"]

df_month_rio = df_rio.groupby("ANO-MES")[["PREÇO MÉDIO REVENDA", "MES"]].last()

df_month_rio[df_month_rio["MES"] == 12]

C:\Users\Matheus\AppData\Local\Temp\ipykernel_31632\3714027759.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["MES"] = df2["DATA FINAL"].apply(lambda x: x.month)

          PREÇO MÉDIO REVENDA  MES
ANO-MES
2004--12                2.296   12
2005--12                2.508   12
2006--12                2.531   12
2007--12                2.540   12
2008--12                2.565   12
2009--12                2.607   12
2010--12                2.660   12
2011--12                2.849   12
2012--12                2.877   12
2013--12                3.072   12
2014--12                3.206   12
2015--12                3.862   12
2016--12                4.002   12
2017--12                4.548   12
2018--12                4.812   12
2019--12                4.995   12
2020--12                4.929   12